### ISSUE TITLE
Change entry after commit

### ISSUE THREAD

**Issue by perbratterud** [NorwegianVeterinaryInstitute/cake-planning#3]
I would like to be able to change the content of the cake plan I have entered earlier, so that I can alter time or room or type of cake.

**Comment by novica** [comment]
In order to have this ability in the app we need to add another input say "secret spice". The spice should not be shown in the table though. 

This can be added in `mod_sidebar.R`.

Then the code should be also updated to check for a unique combination of sorts. Maybe a combination of "spice" and "person" would be enough to make sure one can edit only his/hers entry. But assuming the app grows and someone adds more than one cake, then maybe the date can be used in the check.

Spice doesn't have to be unique if the combination of entries is being checked against for editing. 

A check box "edit previous entry" may be useful also, so that he app goes through the check only if the user has selected that.

**Comment by trishangu** [comment]
This issue is resolved in #23
